# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

workspace 'QuickMobileTextFieldDemo.xcworkspace'
project 'QuickMobileTextFieldDemo.xcodeproj'

target 'QuickMobileTextFieldDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for QuickMobileTextFieldDemo
  pod 'QuickMobileTextField'
end
